#version 450

layout(local_size_x = 16, local_size_y = 16) in;

layout(binding = 0, rgba8) uniform image2D inputImage;
layout(binding = 1, rgba8) uniform image2D outputImage;

void main()
{
	ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy);
	vec4 color = imageLoad(inputImage, pixelCoords);

	float gray = dot(color.rgb, vec3(0.299, 0.587, 0.114));
	imageStore(outputImage, pixelCoords, vec4(vec3(gray), 1.0));
}
