#version 450

layout(local_size_x = 16, local_size_y = 16) in;

layout(binding = 0, rgba16) uniform image2D inputImage;
layout(binding = 1, rgba16) uniform image2D outputImage;

void main()
{
	ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy);
	vec4 color = imageLoad(inputImage, pixelCoords);

	// Reinhard tone mapping
	vec3 toneMapped = color.rgb / (color.rgb + vec3(1.0));
	imageStore(outputImage, pixelCoords, vec4(toneMapped, 1.0));
}
